# Generated by Django 3.2 on 2021-05-01 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('duration', models.IntegerField()),
                ('avatar', models.ImageField(upload_to='projects/')),
            ],
        ),
    ]
